### ISSUE TITLE
--equal + --withGutter prevents Arrange spanning full width of container

### ISSUE THREAD

**Issue by necolas** [suitcss/components-arrange#8]
Bug introduced by #7

Possible fix, but not supported in Android Browser `<4.4` due to use of `calc`.

``` css
.Arrange--withGutter {
  width: calc(100% + var(--Arrange-gutter-size));
}
```
